version: '3'

services:
  web:
    container_name: tarea
    restart: always
    build: .
    ports:
      - 3000:$PORT
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"
    command: mongod --quiet --logpath /dev/null 

